# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        #handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
        #handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        #handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\MongoDbSessionHandler

    #esi: true
    #fragments: true
    php_errors:
        log: true
    form:
        legacy_error_messages: false
    #error_controller: App\Controller\DefaultController::error

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
